import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import VisualEditsMessenger from "@/visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import NavigationTracker from "@/components/NavigationTracker";
import StorageAccessHelper from "@/components/StorageAccessHelper";
import Script from "next/script";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Always mounted → captures runtime + build errors */}
        <ErrorReporter />
        
        {/* Navigation tracking for PreviewFrame route detection */}
        <NavigationTracker />
        
        {/* Storage Access Helper for iframe cookie/localStorage persistence */}
        <StorageAccessHelper />

        <Script
          src="https://pub-7692af728ddb4ddb969fb854fd104d6c.r2.dev/route-messenger.js"
          strategy="afterInteractive"
          data-target-origin="*"
          data-message-type="ROUTE_CHANGE"
          data-include-search-params="true"
          data-only-in-iframe="true"
          data-debug="true"
          data-custom-data='{"appName":"MyNextApp","version":"1.0.0"}'
        />

        {children}
        <VisualEditsMessenger />
      </body>
    </html>
  );
}
